
const ADD_CONNECTION = 'ADD_CONNECTION';
const UPDATE_CONNECTION_STATE = 'UPDATE_CONNECTION_STATE';

const ADD_ENDPOINT = 'ADD_ENDPOINT';
const UPDATE_ENDPOINT_NAME = 'UPDATE_ENDPOINT_NAME';
const UPDATE_ENDPOINT_MODEL = 'UPDATE_ENDPOINT_MODEL';
const UPDATE_ENDPOINT_MANUFACTURER = 'UPDATE_ENDPOINT_MANUFACTURER';

const ADD_SERVICE = 'ADD_SERVICE';
const UPDATE_SERVICE_NAME = 'UPDATE_SERVICE_NAME';
const UPDATE_SERVICE_TYPE = 'UPDATE_SERVICE_TYPE';
const UPDATE_HARDWARE_REVISION = 'UPDATE_HARDWARE_REVISION';

const ADD_PROPERTY = 'ADD_PROPERTY';
const UPDATE_PROPERTY_NAME = 'UPDATE_PROPERTY_NAME';
const UPDATE_PROPERTY_DATATYPE = 'UPDATE_PROPERTY_DATATYPE';
const UPDATE_PROPERTY_SETTABLE = 'UPDATE_PROPERTY_SETTABLE';
const UPDATE_PROPERTY_VALUE = 'UPDATE_PROPERTY_VALUE';

export default {
    ADD_CONNECTION,
    UPDATE_CONNECTION_STATE,
    ADD_ENDPOINT,

    UPDATE_ENDPOINT_NAME,
    UPDATE_ENDPOINT_MODEL,
    UPDATE_ENDPOINT_MANUFACTURER,
    UPDATE_HARDWARE_REVISION,

    ADD_SERVICE,
    UPDATE_SERVICE_NAME,
    UPDATE_SERVICE_TYPE,

    ADD_PROPERTY,
    UPDATE_PROPERTY_NAME,
    UPDATE_PROPERTY_DATATYPE,
    UPDATE_PROPERTY_SETTABLE,
    UPDATE_PROPERTY_VALUE,
}